version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: sayat
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: event_management_system
    ports:
      - "5433:5432"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_management_system
      SPRING_DATASOURCE_USERNAME: sayat
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    depends_on:
      - db
